"""Reader for LeRobot datasets generated by ``ConvertRmbDataToLerobot``.
The standard LeRobot features are read from Parquet/video files, while the
losslessly copied depth videos and MP3 files are read through the asset manifest.
The public interface intentionally resembles :class:`RmbData`.
"""

import json
import os
import subprocess
import threading
from pathlib import Path

import cv2
import numpy as np

try:
    from lerobot.datasets.lerobot_dataset import LeRobotDataset
except ImportError:
    LeRobotDataset = None

from ..utils.FileUtils import parse_lerobot_episode_path
from .DataKey import DataKey
from .RmbData import RmbData


class LeRobotData:
    """Read all standard and v2 supplemental data from a local LeRobot dataset."""

    # A training dataset creates a short-lived LeRobotData instance for every
    # sample.  Keep the costly, read-only LeRobotDataset objects alive per
    # DataLoader worker instead.  PID is part of the key so objects created in
    # the parent process are never reused after DataLoader forks its workers.
    _shared_dataset_cache = {}
    _shared_dataset_cache_lock = threading.Lock()

    class LeRobotFeature:
        """Array-like access to one feature across all dataset frames."""

        def __init__(self, data, key):
            self.data = data
            self.key = key

        def __len__(self):
            return len(self.data)

        def __getitem__(self, index):
            if isinstance(index, slice):
                if self.data._is_numeric_feature(self.key):
                    indexes = range(*index.indices(len(self)))
                    return self.data.get_feature_sequence(self.key, indexes)
                return np.stack([self[idx] for idx in range(*index.indices(len(self)))])
            if isinstance(index, (list, tuple, np.ndarray)):
                if self.data._is_numeric_feature(self.key):
                    return self.data.get_feature_sequence(self.key, index)
                return np.stack([self[int(idx)] for idx in index])
            return self.data._get_feature(self.key, int(index))

        @property
        def shape(self):
            feature = self.data.features[self.key]
            return (len(self.data), *feature["shape"])

        @property
        def dtype(self):
            return np.dtype(self.data.features[self.key]["dtype"])

    class LeRobotDepthVideo:
        """Array-like depth-video access across all episodes."""

        def __init__(self, data, camera_name):
            self.data = data
            self.camera_name = camera_name

        def __len__(self):
            return len(self.data)

        def __getitem__(self, index):
            if isinstance(index, slice):
                return np.stack([self[idx] for idx in range(*index.indices(len(self)))])
            if isinstance(index, (list, tuple, np.ndarray)):
                return np.stack([self[int(idx)] for idx in index])
            return self.data._get_depth_frame(self.camera_name, int(index))

        @property
        def shape(self):
            if len(self) == 0:
                return (0,)
            return (len(self), *self[0].shape)

        @property
        def dtype(self):
            return np.dtype(np.float32)

    def __init__(self, path, enable_cache=False, image_size=None, video_backend=None):
        self.path = Path(path)
        if not (self.path / "meta" / "info.json").is_file():
            raise ValueError(
                f"[{self.__class__.__name__}] '{self.path}' is not a local LeRobot dataset."
            )
        self.enable_cache = enable_cache
        self.image_size = None if image_size is None else tuple(image_size)
        self.video_backend = video_backend
        self.dataset = None
        self._raw_hf_dataset = None
        self._depth_videos = {}
        self._rgb_videos = {}
        self._shared_dataset_handle = None
        self.asset_manifest = {"episodes": {}}
        self.rmb_feature_schema = {}

    def open(self):
        if LeRobotDataset is None:
            raise ImportError(
                f"[{self.__class__.__name__}] The 'lerobot' package is required to read "
                "LeRobot datasets. Install it with `pip install -e ./third_party/lerobot` "
                "or `pip install robo_manip_baselines[lerobot]`."
            )

        if self.dataset is not None:
            self.close()

        cache_key = (os.getpid(), str(self.path.resolve()), self.video_backend)
        with self._shared_dataset_cache_lock:
            handle = self._shared_dataset_cache.get(cache_key)
            if handle is None:
                dataset = LeRobotDataset(
                    repo_id=self.path.name,
                    root=self.path,
                    video_backend=self.video_backend,
                )
                asset_manifest = {"episodes": {}}
                manifest_path = self.path / "meta" / "rmb_assets.json"
                if manifest_path.is_file():
                    with open(manifest_path) as file:
                        asset_manifest = json.load(file)
                rmb_feature_schema = {}
                schema_path = self.path / "meta" / "rmb_schema.json"
                if schema_path.is_file():
                    with open(schema_path) as file:
                        rmb_feature_schema = json.load(file)
                handle = {
                    "dataset": dataset,
                    "raw_hf_dataset": dataset.hf_dataset.with_format(None),
                    "asset_manifest": asset_manifest,
                    "rmb_feature_schema": rmb_feature_schema,
                    # Numeric data are cached lazily by feature key.  This is
                    # inexpensive for state/action and avoids repeatedly
                    # reading the same Parquet values in every epoch.
                    "numeric_features": {},
                }
                self._shared_dataset_cache[cache_key] = handle

        self._shared_dataset_handle = handle
        self.dataset = handle["dataset"]
        self._raw_hf_dataset = handle["raw_hf_dataset"]
        self.asset_manifest = handle["asset_manifest"]
        self.rmb_feature_schema = handle["rmb_feature_schema"]

    def close(self):
        self.dataset = None
        self._raw_hf_dataset = None
        self._shared_dataset_handle = None
        self._depth_videos.clear()
        self._rgb_videos.clear()

    @property
    def closed(self):
        return self.dataset is None

    def __enter__(self):
        self.open()
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        self.close()

    @property
    def attrs(self):
        self._require_open()
        return self.dataset.meta.info

    @property
    def features(self):
        self._require_open()
        return self.dataset.features

    def __len__(self):
        self._require_open()
        return len(self.dataset)

    def _require_open(self):
        if self.closed:
            raise ValueError(f"[{self.__class__.__name__}] The dataset is not open.")

    def _resolve_key(self, key):
        """Accept both LeRobot feature names and the original RMB names."""
        if key in self.features:
            return key
        if DataKey.is_rgb_image_key(key):
            camera_name = DataKey.get_camera_name(key)
            candidate = f"observation.images.{camera_name}_rgb"
            if candidate in self.features:
                return candidate
        aliases = {
            DataKey.MEASURED_JOINT_POS: "observation.state",
            DataKey.COMMAND_JOINT_POS: "action",
            DataKey.MEASURED_JOINT_VEL: "observation.velocity",
            DataKey.TIME: "observation.source_time",
        }
        if key in aliases:
            return aliases[key]
        candidate = f"observation.rmb.{key}"
        if candidate in self.features:
            return candidate
        return None

    def keys(self):
        self._require_open()
        keys = list(self.features)
        for key in list(keys):
            if key.startswith("observation.rmb."):
                keys.append(key.removeprefix("observation.rmb."))
            elif key.startswith("observation.images.") and key.endswith("_rgb"):
                camera_name = key.removeprefix("observation.images.").removesuffix(
                    "_rgb"
                )
                keys.append(DataKey.get_rgb_image_key(camera_name))
        keys.extend(
            [
                DataKey.MEASURED_JOINT_POS,
                DataKey.COMMAND_JOINT_POS,
                DataKey.MEASURED_JOINT_VEL,
                DataKey.TIME,
            ]
        )
        for episode in self.asset_manifest.get("episodes", {}).values():
            for depth in episode.get("depth", []):
                keys.append(DataKey.get_depth_image_key(depth["camera"]))
        return list(dict.fromkeys(keys))

    def __contains__(self, key):
        return key in self.keys()

    def __getitem__(self, key):
        self._require_open()
        feature_key = self._resolve_key(key)
        if feature_key is not None:
            return self.LeRobotFeature(self, feature_key)
        if DataKey.is_depth_image_key(key):
            camera_name = DataKey.get_camera_name(key)
            if any(
                depth["camera"] == camera_name
                for episode in self.asset_manifest.get("episodes", {}).values()
                for depth in episode.get("depth", [])
            ):
                return self.LeRobotDepthVideo(self, camera_name)
        raise KeyError(key)

    def _get_feature(self, key, frame_index):
        feature = self.features[key]
        if feature["dtype"] in ("image", "video"):
            if key.startswith("observation.images.") and key.endswith("_rgb"):
                camera_name = key.removeprefix("observation.images.").removesuffix(
                    "_rgb"
                )
                if any(
                    item["camera"] == camera_name
                    for episode in self.asset_manifest.get("episodes", {}).values()
                    for item in episode.get("rgb", [])
                ):
                    return self._get_rgb_frame(camera_name, frame_index)
            value = self.dataset[frame_index][key].permute(1, 2, 0).numpy()
            image = np.rint(value * 255).astype(np.uint8)
            if self.image_size is not None:
                image = cv2.resize(
                    image, self.image_size, interpolation=cv2.INTER_LINEAR
                )
            return image
        return self._get_numeric_feature_array(key)[frame_index]

    def _is_numeric_feature(self, key):
        return self.features[key]["dtype"] not in ("image", "video")

    def _get_numeric_feature_array(self, key):
        """Return a process-local NumPy cache for one numeric feature."""
        self._require_open()
        if not self._is_numeric_feature(key):
            raise KeyError(f"'{key}' is not a numeric LeRobot feature")

        numeric_features = self._shared_dataset_handle["numeric_features"]
        with self._shared_dataset_cache_lock:
            values = numeric_features.get(key)
            if values is None:
                dtype, shape = self._numeric_spec(key)
                values = np.asarray(self._raw_hf_dataset[key], dtype=dtype)
                values = values.reshape(len(self), *shape)
                numeric_features[key] = values
        return values

    def _numeric_spec(self, key):
        feature = self.features[key]
        schema = self.rmb_feature_schema.get(key)
        dtype = np.dtype(schema["dtype"] if schema else feature["dtype"])
        if schema is not None:
            shape = tuple(schema["shape"])
        elif key in ("observation.source_time", "reward"):
            shape = ()
        else:
            shape = tuple(feature["shape"])
        return dtype, shape

    def get_feature_sequence(self, key, indexes):
        """Return a numeric feature for selected global frame indexes efficiently."""
        self._require_open()
        feature_key = self._resolve_key(key)
        if feature_key is None or not self._is_numeric_feature(feature_key):
            raise KeyError(f"'{key}' is not a numeric LeRobot feature")
        indexes = list(map(int, indexes))
        return self._get_numeric_feature_array(feature_key)[indexes]

    def _get_rgb_frame(self, camera_name, frame_index):
        metadata = self._raw_hf_dataset[frame_index]
        episode = self.get_episode_assets(int(metadata["episode_index"]))
        rgb = next(item for item in episode["rgb"] if item["camera"] == camera_name)
        path = self.path / rgb["path"]
        if path not in self._rgb_videos:
            self._rgb_videos[path] = RmbData.RmbRgbVideo(
                str(path), enable_cache=self.enable_cache, image_size=self.image_size
            )
        return self._rgb_videos[path][int(metadata["frame_index"])]

    def _get_depth_frame(self, camera_name, frame_index):
        metadata = self.dataset.hf_dataset[frame_index]
        episode_index = int(metadata["episode_index"])
        local_index = int(metadata["frame_index"])
        episode = self.get_episode_assets(episode_index)
        depth = next(item for item in episode["depth"] if item["camera"] == camera_name)
        path = self.path / depth["path"]
        if path not in self._depth_videos:
            self._depth_videos[path] = RmbData.RmbDepthVideo(
                str(path), enable_cache=self.enable_cache, image_size=self.image_size
            )
        return self._depth_videos[path][local_index]

    def get_frame(self, frame_index, include_depth=True):
        """Return every LeRobot feature and the episode's supplemental assets."""
        self._require_open()
        frame = {key: self._get_feature(key, frame_index) for key in self.features}
        metadata = self.dataset.hf_dataset[frame_index]
        episode_index = int(metadata["episode_index"])
        frame["assets"] = self.get_episode_assets(episode_index)
        if include_depth:
            frame["depth_images"] = {
                depth["camera"]: self._get_depth_frame(depth["camera"], frame_index)
                for depth in frame["assets"].get("depth", [])
            }
        return frame

    def get_episode_assets(self, episode_index):
        """Return the MP3/depth paths and camera metadata for one episode."""
        self._require_open()
        try:
            return self.asset_manifest["episodes"][str(int(episode_index))]
        except KeyError as error:
            raise KeyError(f"No v2 assets for episode {episode_index}") from error

    def load_audio(self, episode_index, audio_index=0):
        """Decode one MP3 asset to mono float32 samples and return ``(samples, hz)``."""
        asset = self.get_episode_assets(episode_index)["audio"][audio_index]
        sample_rate_hz = int(asset["sample_rate_hz"])
        path = self.path / asset["path"]
        result = subprocess.run(
            [
                "ffmpeg",
                "-v",
                "error",
                "-i",
                str(path),
                "-f",
                "f32le",
                "-ac",
                "1",
                "-ar",
                str(sample_rate_hz),
                "pipe:1",
            ],
            check=True,
            stdout=subprocess.PIPE,
        )
        return np.frombuffer(result.stdout, dtype=np.float32), sample_rate_hz


class LeRobotEpisodeData:
    """Single-episode view of a local LeRobot dataset with an RmbData-like interface.

    Instances are constructed from a virtual episode path ``<dataset_dir>@<episode_idx>``
    as enumerated by :func:`find_rmb_files`. ``RmbData(...)`` transparently returns an
    instance of this class for such paths, so the training pipeline can consume LeRobot
    datasets without modification.
    """

    class EpisodeFeatureView:
        """Episode-local array-like view of a :class:`LeRobotData.LeRobotFeature`."""

        def __init__(self, feature, start, stop):
            self.feature = feature
            self.start = start
            self.stop = stop

        def __len__(self):
            return self.stop - self.start

        def _to_global_index(self, index):
            index = int(index)
            if index < 0:
                index += len(self)
            if not 0 <= index < len(self):
                raise IndexError(
                    f"[{self.__class__.__name__}] Index {index} out of range for episode of length {len(self)}."
                )
            return self.start + index

        def __getitem__(self, index):
            if isinstance(index, slice):
                indexes = [
                    self._to_global_index(idx)
                    for idx in range(*index.indices(len(self)))
                ]
                return self.feature[indexes]
            if isinstance(index, (list, tuple, np.ndarray)):
                return self.feature[[self._to_global_index(idx) for idx in index]]
            return self.feature[self._to_global_index(index)]

        @property
        def shape(self):
            return (len(self), *self.feature.shape[1:])

        @property
        def dtype(self):
            return self.feature.dtype

    def __init__(self, path, enable_cache=False, mode="r", image_size=None):
        parsed = parse_lerobot_episode_path(str(path))
        if parsed is None:
            raise ValueError(
                f"[{self.__class__.__name__}] Invalid LeRobot episode path "
                f"(expected '<dataset_dir>@<episode_idx>'): {path}"
            )
        if mode != "r":
            raise ValueError(
                f"[{self.__class__.__name__}] LeRobot datasets are read-only (mode='{mode}')."
            )
        self.path = str(path)
        self.dataset_dir, self.episode_idx = parsed
        self.enable_cache = enable_cache
        self.mode = mode
        self.image_size = None if image_size is None else tuple(image_size)
        self._flat = LeRobotData(
            self.dataset_dir, enable_cache=enable_cache, image_size=image_size
        )
        self._start = None
        self._stop = None
        self._episode_assets = {}
        self._attrs = None

    def open(self):
        self._flat.open()
        episode = self._flat.dataset.meta.episodes[self.episode_idx]
        self._start = int(episode["dataset_from_index"])
        self._stop = int(episode["dataset_to_index"])
        self._episode_assets = self._flat.asset_manifest.get("episodes", {}).get(
            str(self.episode_idx), {}
        )
        self._attrs = self._make_attrs(episode)

    def close(self):
        self._flat.close()

    @property
    def closed(self):
        return self._flat.closed

    def __enter__(self):
        self.open()
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        self.close()

    def _require_open(self):
        if self.closed:
            raise ValueError(f"[{self.__class__.__name__}] The dataset is not open.")

    def _make_attrs(self, episode):
        """Synthesize an RmbData-like attrs dict from the LeRobot metadata."""
        attrs = {
            "format": "LeRobotData-v3",
            "episode_index": self.episode_idx,
            "camera_names": [
                key.removeprefix("observation.images.").removesuffix("_rgb")
                for key in self._flat.features
                if key.startswith("observation.images.") and key.endswith("_rgb")
            ],
        }
        tasks = episode.get("tasks")
        if tasks:
            attrs["task_desc"] = tasks[0]
        for depth in self._episode_assets.get("depth", []):
            if "fovy" in depth:
                depth_key = DataKey.get_depth_image_key(depth["camera"])
                attrs[f"{depth_key}_fovy"] = depth["fovy"]
        if "source_rmb" in self._episode_assets:
            attrs["source_rmb"] = self._episode_assets["source_rmb"]
        return attrs

    @property
    def attrs(self):
        self._require_open()
        return self._attrs

    def keys(self):
        self._require_open()
        return self._flat.keys()

    def __contains__(self, key):
        return key in self.keys()

    def __getitem__(self, key):
        self._require_open()
        feature_key = self._flat._resolve_key(key)
        if feature_key is not None:
            if self._flat._is_numeric_feature(feature_key):
                return self._flat._get_numeric_feature_array(feature_key)[
                    self._start : self._stop
                ]
            # RGB image feature: prefer the losslessly copied per-episode asset video
            asset_video = self._get_rgb_asset_video(feature_key)
            if asset_video is not None:
                return asset_video
            return self.EpisodeFeatureView(
                LeRobotData.LeRobotFeature(self._flat, feature_key),
                self._start,
                self._stop,
            )
        if DataKey.is_depth_image_key(key):
            camera_name = DataKey.get_camera_name(key)
            for depth in self._episode_assets.get("depth", []):
                if depth["camera"] == camera_name:
                    return RmbData.RmbDepthVideo(
                        str(Path(self.dataset_dir) / depth["path"]),
                        enable_cache=self.enable_cache,
                        image_size=self.image_size,
                    )
        raise KeyError(key)

    def _get_rgb_asset_video(self, feature_key):
        if not (
            feature_key.startswith("observation.images.")
            and feature_key.endswith("_rgb")
        ):
            return None
        camera_name = feature_key.removeprefix("observation.images.").removesuffix(
            "_rgb"
        )
        for rgb in self._episode_assets.get("rgb", []):
            if rgb["camera"] == camera_name:
                return RmbData.RmbRgbVideo(
                    str(Path(self.dataset_dir) / rgb["path"]),
                    enable_cache=self.enable_cache,
                    image_size=self.image_size,
                )
        return None

    def dump_to_hdf5(self, dst_path, force_overwrite=False):
        raise NotImplementedError(
            f"[{self.__class__.__name__}] Dumping LeRobot episodes is not supported."
        )

    def dump_to_rmb(self, dst_path, force_overwrite=False):
        raise NotImplementedError(
            f"[{self.__class__.__name__}] Dumping LeRobot episodes is not supported."
        )
